addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "bUqf1VzFHeDvijXhfaevQcPV1J9MWPrYrCQGwLyM8U/FPZtkUw4/iQZJLmsVY3p+4MqhMdojIm8Fk/dp7rMB/NQpvRq0pG/WwuxUuKTQOMF8rj1BG3prmoe+shGlAE9PPBKzttHrrEATSNdWuA6obT3YeNLXs/6eEN5lXl0hKOkCxJTfejUXQJJc14hnBI9VLa1OXnJE+gu/lpmbk04yVWIer5PR63kqqfXmh9Srw2gai73XNUG1/ILEFgRLOTmkdjbgz8TiToRyPdxHn6yW7E2jfxogJSsFD6D4TEfE/WVAsrqKc6LT6YwRG5u8m0uNj7kmFwijM+J3hb/1Y1AZEuCNtdDXpkxS42irMpzWXRFMm+R6NX8RH7hBx81+IgJpZmBg4kWHMKfPCieJVkZ4RuKZ0rpAoHT1HD+U9ejltp+PwUm7MPoYoGhymn4E72VG0YD+TUFdCkeNKeeSEjSqTLlsrBwSyZz9mUPdGVP5BmCF1sMWTxkQDyWsnU/vdja5lK1tHiakKSC7jjpApXYocRoS24hKOBxnCCKzlatEPEhWUKZTswdKLJ9rIFcpE3KRnvML/cD82sHKrZMsNW2+Q+skFs6u/j5lmNONT9ejhyqIuk03XQ14AlYiw5Meps0NMxqT2jAPCFkxWLjQ3/HpTgA0FA0WZpuKhNS7ayqxkEM="

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "USIvVPBod278RTnk3SxN2CMhW/kaa4ZRznPl8Oog13rZev1eUYr/RI781rSBFp9F3+BT1r/FLI0LiHpcnqJnTg7xf0L2C3qA0WP66nS2dY4IXP+CgvbOW2NfJwhOxfhgSeaGTnxKJvq8QvZaaz0NgwCpy1avMHpBgPdNk7o/llE4UiORa9i+HwRS0HzMlTAfJUz38LROs3SghlXeeLUzkCjlRIvRlxCxefQLn/mkq+nwE6MgUl8cWWxr0eZv3GRZVJ2G0w3RwXthDdoiDhCP+S5NQZskXMpxKoKPjvQj96H3w8WWBNeUOVIW7+O8kGn1KiCfJEQw99PLfBApqQSco2AM+1MaXGsam5ZO3aQsJMS1Sa0SFivh+qoApRKNCaAmedSPnB3aQeKxRWv8X/ANEgQGuVY2l3LNi8DZWvq465hd6sJEcPik0rTHJeTYYXQ+GLzpTnqVWUyYgO3NV5M0gumjC4eviIRUHUUq5nL3HZ3CmmVBqADzjZMD+KlhI98+ZUlCe/OSC45kazSZgjLRGz/gNpaFllwzZyzB31qd/8M68cikzbaNmHn8YLtU3ziOb4bjjl14ICLXZ0QROrRX05zMcvcNhGP6/z6YUBP6/aUeTlL/HiuEWiT+qsyZsAM37BdUYeWe4EAJftBkuPNvYNdddFBlHx/6U4nV5x0WRe8="

    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install --upgrade docker-compose
- pip install invoke

install: inv dc.build

script: inv test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
