addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "AGq8kaZhYgpkzPxqVXcPSuKZLAf6ucBj4OtJmS594Zb1oGWTIbe7NaVZGh0kb7tW47HhHHPU+y/7cKKLhayT8l0TWjpoTKw+ttxgvJcvk2E8IkGzJWeiSHolx+v6fwWs5wxl7MSpNBX56Aqz1Lp++lpkcUt4VqAei3E2rvUTsyAORdElMToR6sW9lJvzCWza3E0Htim2U26sW6M+zqKGIGn6HpVAMzEUvPh4OaqiigZjl5NMHbY5XMHdsyGEW8izfneuTExKwxrPX4UwF2ASZZyi8PXaRnuG+CC6b9tALBqu3T34al16JaaCJGxOHfFSd92nqFPsFt16hKbgFOdzTSNjXg6d4FgBYPb+LLnfZa0UuDEpKAVoeh53ktFSS1wtJ18QOAGZfIdjMir0rQR4Xb2XQQXNivBlP2O8em0tolnpNsFLb/WeSw0kXoijCUDdwZeOTPQZcdv5cMBvpLMEqnSm5jZP8gKs2b3ED2HTgoPB52aPmjpANp6dNT3YL0p4hlr5JytG358lhfuzqMlsv088JYQ6sx782D9Ie4orpBPIBJZT88B/C4fozeyPbEqiWywL9asFHVxuDaJlPccEHa+omN3bngBg+WY61xqAutdbM6h+d4vJtn5l7nIbXjgZEzT/yZKhpCBa/nuA+d9S31OoQFJLt4+vvdeimeCXQUY="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "OZIY7P6PxsZvSAHgoV96Bpo4JMdAOEueKQu2w8WW2L0epeO18CSZ/7pknXvHt7wpK4vP3VyxYP0DEsRjkNnZ9j0xq9n6Rm+7zreoNGycI948+KOOLoji/SN+l42elr8QfY4d+e56F0W1NUlqevCHqYVURpjwQoQ5NPZ3j8I1AiNCQppQhnPwcUjCzDAbrxvaXEi1sBR8jpLYZ8AIa6jjzdmhGsLM5Y4xLGOldXLLT6Crs/0yNqk+35dcsXx1NETgm+33hPqqgDEwHrpmXqwwyrri3qbTZFT7RQh9WvX71I4AMmR78ssW1G7Zvnf1GpmIP2iCMxy0R8Eo5tzvdpHOhrFSmqz+dV1Mc/y2Da76d9dJTU5EuP8+pzw9vUA0zye1Tc9y63371DYjHBYB1bgtnFaPAqd60ffgip1tO5L7jhPqvhBbJd85GYlomi7X0Cnz+sZGOe+5TcSI1iaU+CePJnO3Xyz5+iDtlVmEDsx4ATLDBoPMgZWphJyQYZMYUD2HhRuV1et+mI9bA00FN1VstJPPMftckMYmp7LQvwW7f9+6UFq+jhA2e8iHTshS7Z5fbB/rT+s7qCGu1WQtQPpkuVWxg4rcaD+izQODs0F6n3hG1u0S4ecBWhzQHEWYos2+0CsrXsgwU1t4QVxTNbF7aEPlBxufLsMtM9jmjVqSXHM="
    on_success: always
    on_failure: always

before_install:
- pip install --upgrade docker-compose
- source scripts/ci/environment.sh

install: docker-compose build

before_script:
- docker-compose up -d
- sleep 10

script: inv tests

after_success:
- ci-tag-build
- hub-push
