apiVersion: v1
kind: Service
metadata:
  name: couchdbbal
spec:
  selector:
    app: couchdb
    project: valuphone
    environment: production
  ports:
    - name: data
      protocol: TCP
      port: 5984
    - name: admin
      protocol: TCP
      port: 5986
