kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: couchdb-data-couchdb-0
  labels:
    app: couchdb
    project: valuphone
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: couchdb-data-couchdb-1
  labels:
    app: couchdb
    project: valuphone
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: couchdb-data-couchdb-2
  labels:
    app: couchdb
    project: valuphone
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
